// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package convertors is a generated datamapper package.
package convertors

import (
	"github.com/underbek/datamapper/_test_data/mapper/with_dash_and_pointers/dao"
	"github.com/underbek/datamapper/_test_data/mapper/with_dash_and_pointers/domain"
)

// ConvertDomainAdditionalToDaoAdditional convert domain.Additional by tag map to dao.Additional by tag db
func ConvertDomainAdditionalToDaoAdditional(from domain.Additional) dao.Additional {
	return dao.Additional{
		Key:   from.Key,
		Value: from.Value,
	}
}

// ConvertDaoAdditionalToDomainAdditional convert dao.Additional by tag db to domain.Additional by tag map
func ConvertDaoAdditionalToDomainAdditional(from dao.Additional) domain.Additional {
	return domain.Additional{
		Key:   from.Key,
		Value: from.Value,
	}
}
