// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package mapper is a generated datamapper package.
package mapper

import (
	"errors"

	f "github.com/underbek/datamapper/_test_data/mapper/recursive/from"
	t "github.com/underbek/datamapper/_test_data/mapper/recursive/to"
	"github.com/underbek/datamapper/converts"
)

// ConvertFUserToTUser convert f.User by tag recursive to t.User by tag recursive
func ConvertFUserToTUser(from f.User) (t.User, error) {
	if from.Account == nil {
		return t.User{}, errors.New("cannot convert f.User.Account -> t.User.Account, field is nil")
	}

	return t.User{
		ID:      converts.ConvertNumericToString(from.ID),
		Account: ConvertFAccountToTAccount(*from.Account),
	}, nil
}
