// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package with_one_import is a generated datamapper package.
package with_one_import

import "github.com/underbek/datamapper/converts"

// ConvertFromToTo convert From by tag map to To by tag map
func ConvertFromToTo(from From) To {
	return To{
		UUID: converts.ConvertNumericToString(from.ID),
		Name: from.Name,
	}
}
