// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package mapper is a generated datamapper package.
package mapper

import (
	"errors"
	"fmt"

	"github.com/underbek/datamapper/_test_data/mapper/convertors"
	"github.com/underbek/datamapper/_test_data/mapper/domain"
	api "github.com/underbek/datamapper/_test_data/mapper/transport"
	"github.com/underbek/datamapper/converts"
)

// ConvertApiUserToDomainUser convert *api.User by tag map to domain.User by tag map
func ConvertApiUserToDomainUser(from *api.User) (domain.User, error) {
	if from == nil {
		return domain.User{}, errors.New("User is nil")
	}

	fromAge, err := converts.ConvertStringToDecimal(from.Age)
	if err != nil {
		return domain.User{}, fmt.Errorf("convert User.Age -> User.Age failed: %w", err)
	}

	var fromChildCount *int
	if from.ChildCount != nil {
		res, err := converts.ConvertStringToSigned[int](*from.ChildCount)
		if err != nil {
			return domain.User{}, fmt.Errorf("convert User.ChildCount -> User.ChildCount failed: %w", err)
		}

		fromChildCount = &res
	}

	return domain.User{
		ID:         convertors.CustomUUIDToInteger[int](from.UUID),
		Name:       from.Name,
		Age:        fromAge,
		ChildCount: fromChildCount,
	}, nil
}

// ConvertApiUserSliceToDomainUserSlice convert []*api.User to []domain.User
func ConvertApiUserSliceToDomainUserSlice(fromSlice []*api.User) ([]domain.User, error) {
	if fromSlice == nil {
		return nil, nil
	}

	toSlice := make([]domain.User, 0, len(fromSlice))
	for _, from := range fromSlice {
		to, err := ConvertApiUserToDomainUser(from)
		if err != nil {
			return nil, fmt.Errorf("convert []*api.User to []domain.User failed: %w", err)
		}
		toSlice = append(toSlice, to)
	}

	return toSlice, nil
}

// ConvertDomainUserToApiUser convert domain.User by tag map to *api.User by tag map
func ConvertDomainUserToApiUser(from domain.User) *api.User {
	var fromChildCount *string
	if from.ChildCount != nil {
		res := converts.ConvertNumericToString(*from.ChildCount)
		fromChildCount = &res
	}

	return &api.User{
		UUID:       convertors.CustomIntegerToUUID(from.ID),
		Name:       from.Name,
		Age:        converts.ConvertDecimalToString(from.Age),
		ChildCount: fromChildCount,
	}
}

// ConvertDomainUserSliceToApiUserSlice convert []domain.User to []*api.User
func ConvertDomainUserSliceToApiUserSlice(fromSlice []domain.User) []*api.User {
	if fromSlice == nil {
		return nil
	}

	toSlice := make([]*api.User, 0, len(fromSlice))
	for _, from := range fromSlice {
		toSlice = append(toSlice, ConvertDomainUserToApiUser(from))
	}

	return toSlice
}
