// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package with_aliases is a generated datamapper package.
package with_aliases

import (
	cfalias "github.com/underbek/datamapper/_test_data/generator/with_aliases/cf"
	fromalias "github.com/underbek/datamapper/_test_data/generator/with_aliases/from"
	toalias "github.com/underbek/datamapper/_test_data/generator/with_aliases/to"
)

// ConvertFromaliasFromToToaliasTo convert fromalias.From by tag map to toalias.To by tag map
func ConvertFromaliasFromToToaliasTo(from fromalias.From) toalias.To {
	return toalias.To{
		UUID: cfalias.ConvertNumericToString(from.ID),
		Name: from.Name,
	}
}
