// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package with_aliases is a generated datamapper package.
package with_aliases

import (
	fromalias "github.com/underbek/datamapper/_test_data/generator/with_aliases/from"
	toalias "github.com/underbek/datamapper/_test_data/generator/with_aliases/to"
)

// ConvertFromaliasFromSliceToToaliasToSlice convert []fromalias.From to []toalias.To
func ConvertFromaliasFromSliceToToaliasToSlice(fromSlice []fromalias.From) []toalias.To {
	if fromSlice == nil {
		return nil
	}

	toSlice := make([]toalias.To, 0, len(fromSlice))
	for _, from := range fromSlice {
		toSlice = append(toSlice, ConvertFromaliasFromToToaliasTo(from))
	}

	return toSlice
}
