// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package other_package_model is a generated datamapper package.
package other_package_model

import (
	"github.com/underbek/datamapper/_test_data/generator/other_package_model/other"
	"github.com/underbek/datamapper/converts"
)

// ConvertOtherFromToTo convert other.From by tag map to To by tag map
func ConvertOtherFromToTo(from other.From) To {
	return To{
		UUID: converts.ConvertNumericToString(from.ID),
		Name: from.Name,
	}
}
