// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package other_package_model is a generated datamapper package.
package other_package_model

import "github.com/underbek/datamapper/_test_data/generator/other_package_model/other"

// ConvertOtherFromSliceToToSlice convert []other.From to []To
func ConvertOtherFromSliceToToSlice(fromSlice []other.From) []To {
	if fromSlice == nil {
		return nil
	}

	toSlice := make([]To, 0, len(fromSlice))
	for _, from := range fromSlice {
		toSlice = append(toSlice, ConvertOtherFromToTo(from))
	}

	return toSlice
}
