// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package mapper is a generated datamapper package.
package mapper

import (
	customCf "github.com/underbek/datamapper/_test_data/mapper/convertors"
	to "github.com/underbek/datamapper/_test_data/mapper/domain"
	from "github.com/underbek/datamapper/_test_data/mapper/transport"
	"github.com/underbek/datamapper/converts"
)

// ConvertFromUserToToUser convert from.User by tag map to to.User by tag map
func ConvertFromUserToToUser(from from.User) (to.User, error) {
	fromAge, err := converts.ConvertStringToDecimal(from.Age)
	if err != nil {
		return to.User{}, err
	}

	var fromChildCount *int
	if from.ChildCount != nil {
		res, err := converts.ConvertStringToSigned[int](*from.ChildCount)
		if err != nil {
			return to.User{}, err
		}

		fromChildCount = &res
	}

	return to.User{
		ID:         customCf.CustomUUIDToInteger[int](from.UUID),
		Name:       from.Name,
		Age:        fromAge,
		ChildCount: fromChildCount,
	}, nil
}
