// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package with_field_pointers_without_error is a generated datamapper package.
package with_field_pointers_without_error

import (
	"github.com/shopspring/decimal"
	"github.com/underbek/datamapper/converts"
)

// ConvertFromToTo convert From by tag map to To by tag map
func ConvertFromToTo(from From) To {
	var fromAge *decimal.Decimal
	if from.Age != nil {
		res := converts.ConvertFloatToDecimal(*from.Age)
		fromAge = &res
	}

	return To{
		UUID: &from.ID,
		Name: from.Name,
		Age:  fromAge,
	}
}
