// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package without_imports is a generated datamapper package.
package without_imports

// ConvertFromToTo convert From by tag map to To by tag map
func ConvertFromToTo(from From) To {
	return To{
		Name: from.Name,
	}
}
