// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package mapper is a generated datamapper package.
package mapper

import (
	"errors"
	"fmt"

	f "github.com/underbek/datamapper/_test_data/mapper/recursive/from"
	t "github.com/underbek/datamapper/_test_data/mapper/recursive/to"
	"github.com/underbek/datamapper/converts"
)

// ConvertFUserToTUser convert f.User by tag recursive to t.User by tag recursive
func ConvertFUserToTUser(from f.User) (t.User, error) {
	if from.Account == nil {
		return t.User{}, errors.New("cannot convert f.User.Account -> t.User.Account, field is nil")
	}

	return t.User{
		ID:      converts.ConvertNumericToString(from.ID),
		Account: ConvertFAccountToTAccount(*from.Account),
	}, nil
}

// ConvertTUserToFUser convert t.User by tag recursive to f.User by tag recursive
func ConvertTUserToFUser(from t.User) (f.User, error) {
	fromID, err := converts.ConvertStringToSigned[int64](from.ID)
	if err != nil {
		return f.User{}, fmt.Errorf("convert User.ID -> User.ID failed: %w", err)
	}

	fromAccount, err := ConvertTAccountToFAccount(from.Account)
	if err != nil {
		return f.User{}, fmt.Errorf("convert User.Account -> User.Account failed: %w", err)
	}

	return f.User{
		ID:      fromID,
		Account: &fromAccount,
	}, nil
}
