// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package mapper is a generated datamapper package.
package mapper

import (
	"fmt"

	"github.com/underbek/datamapper/_test_data/mapper/domain"
	"github.com/underbek/datamapper/_test_data/mapper/transport"
)

// ConvertTransportOrderToDomainOrder convert transport.Order by tag map to domain.Order by tag map
func ConvertTransportOrderToDomainOrder(from transport.Order) (domain.Order, error) {
	fromUser, err := ConvertTransportUserToDomainUser(from.User)
	if err != nil {
		return domain.Order{}, fmt.Errorf("convert Order.User -> Order.User failed: %w", err)
	}

	return domain.Order{
		User: fromUser,
	}, nil
}
