// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package cf_with_slice is a generated datamapper package.
package cf_with_slice

import (
	"github.com/shopspring/decimal"
	"github.com/underbek/datamapper/_test_data/generator/cf_with_slice/cf"
)

// ConvertFromToTo convert From by tag map to To by tag map
func ConvertFromToTo(from From) To {
	fromIDs := make([]decimal.Decimal, 0, len(from.IDs))
	for _, item := range from.IDs {
		fromIDs = append(fromIDs, cf.ConvertIntegerToDecimal(item))
	}

	return To{
		UUIDs: fromIDs,
		Ages:  cf.ConvertStringSliceToDecimalSlice(from.Ages),
	}
}
