// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package with_field_slice_and_pointers is a generated datamapper package.
package with_field_slice_and_pointers

import (
	"errors"

	"github.com/shopspring/decimal"
	"github.com/underbek/datamapper/_test_data/generator/with_field_slice_and_pointers/cf"
)

// ConvertFromToTo convert From by tag map to To by tag map
func ConvertFromToTo(from From) (To, error) {
	fromIDs := make([]*int, 0, len(from.IDs))
	for _, item := range from.IDs {
		res := cf.ConvertDecimalToInt(item)

		fromIDs = append(fromIDs, &res)
	}

	fromAges := make([]int, 0, len(from.Ages))
	for _, item := range from.Ages {
		if item == nil {
			return To{}, errors.New("cannot convert From.Ages -> To.Ages, field is nil")
		}

		fromAges = append(fromAges, cf.ConvertDecimalToInt(*item))
	}

	fromCounts := make([]*decimal.Decimal, 0, len(from.Counts))
	for _, item := range from.Counts {
		var resPtr *decimal.Decimal
		if item != nil {
			res := cf.ConvertIntegerToDecimal(*item)
			resPtr = &res
		}

		fromCounts = append(fromCounts, resPtr)
	}

	fromOrigins := make([]*decimal.Decimal, 0, len(from.Origins))
	for _, item := range from.Origins {
		fromOrigins = append(fromOrigins, cf.ConvertFloatPtrToDecimalPtr(item))
	}

	fromKeys := make([]int, 0, len(from.Keys))
	for _, item := range from.Keys {
		if item == nil {
			return To{}, errors.New("cannot convert From.Keys -> To.Keys, field is nil")
		}

		fromKeys = append(fromKeys, *item)
	}

	fromValues := make([]*string, 0, len(from.Values))
	for _, item := range from.Values {
		res := item
		fromValues = append(fromValues, &res)
	}

	return To{
		UUIDs:   fromIDs,
		Ages:    fromAges,
		Counts:  fromCounts,
		Origins: fromOrigins,
		Keys:    fromKeys,
		Values:  fromValues,
	}, nil
}
