// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package with_field_pointers_and_convertors is a generated datamapper package.
package with_field_pointers_and_convertors

import (
	"errors"

	"github.com/shopspring/decimal"
	"github.com/underbek/datamapper/converts"
)

// ConvertFromToTo convert From by tag map to To by tag map
func ConvertFromToTo(from From) (To, error) {
	fromID := converts.ConvertNumericToString(from.ID)

	if from.Age == nil {
		return To{}, errors.New("cannot convert From.Age -> To.Age, field is nil")
	}

	var fromChildren *decimal.Decimal
	if from.Children != nil {
		res := converts.ConvertIntegerToDecimal(*from.Children)
		fromChildren = &res
	}

	return To{
		UUID:     &fromID,
		Age:      converts.ConvertFloatToDecimal(*from.Age),
		Children: fromChildren,
	}, nil
}
