// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package cf_with_pointers_and_erros is a generated datamapper package.
package cf_with_pointers_and_erros

import "github.com/underbek/datamapper/_test_data/generator/cf_with_pointers_and_errors/cf"

// ConvertFromToTo convert From by tag map to To by tag map
func ConvertFromToTo(from From) (To, error) {
	fromID, err := cf.ConvertIntToDecimalPtr(from.ID)
	if err != nil {
		return To{}, err
	}

	fromAge, err := cf.ConvertIntPtrToDecimal(from.Age)
	if err != nil {
		return To{}, err
	}

	fromCount, err := cf.ConvertIntPtrToDecimalPtr(from.Count)
	if err != nil {
		return To{}, err
	}

	fromOrig, err := cf.ConvertIntToDecimal(from.Orig)
	if err != nil {
		return To{}, err
	}

	return To{
		UUID:  fromID,
		Age:   fromAge,
		Count: fromCount,
		Orig:  fromOrig,
	}, nil
}
