// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package with_from_and_to_pointers_without_errors is a generated datamapper package.
package with_from_and_to_pointers_without_errors

// ConvertFromSliceToToSlice convert []*From to []*To
func ConvertFromSliceToToSlice(fromSlice []*From) []*To {
	if fromSlice == nil {
		return nil
	}

	toSlice := make([]*To, 0, len(fromSlice))
	for _, from := range fromSlice {
		toSlice = append(toSlice, ConvertFromToTo(from))
	}

	return toSlice
}
