// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package same_cf_path is a generated datamapper package.
package same_cf_path

// ConvertFromToTo convert From by tag map to To by tag map
func ConvertFromToTo(from From) To {
	return To{
		UUID: ConvertNumericToString(from.ID),
		Name: from.Name,
		Age:  ConvertFloatToDecimal(from.Age),
	}
}
