// Code generated by datamapper.
// https://github.com/underbek/datamapper

// Package mapper is a generated datamapper package.
package mapper

import (
	"github.com/underbek/datamapper/_test_data/mapper/with_dash/simple/from"
	"github.com/underbek/datamapper/_test_data/mapper/with_dash/simple/to"
	"github.com/underbek/datamapper/_test_data/mapper/with_dash/simple/to/to_meta"
	"github.com/underbek/datamapper/converts"
)

// ConvertFromUserDataToToUserData convert from.UserData by tag map to to.UserData by tag map
func ConvertFromUserDataToToUserData(from from.UserData) to.UserData {
	return to.UserData{
		Age: converts.ConvertFloatToDecimal(from.Meta.Age),
		User: to.User{
			UUID: converts.ConvertNumericToString(from.User.ID),
			Name: from.User.Name,
			MetaData: to_meta.Meta{
				Count: converts.ConvertIntegerToDecimal(from.Meta.Count),
			},
		},
	}
}
